import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after,before,describe,it } from "node:test";
import { Ed25519Signer } from "../src/core/signing.js";
import { ProductRepository,type ProductDb } from "../src/product/productRepository.js";
import { createProductProviderRuntime } from "../src/product/providerRuntimeFactory.js";
import { buildProductServer } from "../src/product/server.js";
import { NystDecisionWebhookWorker } from "../src/product/webhookWorker.js";
import type { TenantScope } from "../src/product/types.js";
import { createPostgresStore } from "../src/store/postgresStore.js";
import { MutableClock } from "./githubHelpers.js";
import { runtimeInput } from "./runtimeHelpers.js";
const databaseUrl=process.env.DATABASE_URL;
describe("Nyst v0.2 PostgreSQL product controls",{skip:databaseUrl?false:"DATABASE_URL not set — no database to test against"},()=>{
  let pool:ProductDb&{end():Promise<void>};let store:Awaited<ReturnType<typeof createPostgresStore>>;let repository:ProductRepository;let tenant:TenantScope&{user_id:string};let other:TenantScope&{user_id:string};let app:Awaited<ReturnType<typeof buildProductServer>>;let auth:{cookie:string;csrf:string;session:string};let fakeEffect:string;let fakeSpecVersion:string;const suffix=randomUUID().slice(0,8);
  before(async()=>{const pg=await import("pg") as unknown as{default:{Pool:new(options:{connectionString:string})=>ProductDb&{end():Promise<void>}}};pool=new pg.default.Pool({connectionString:databaseUrl!});store=await createPostgresStore(databaseUrl!);repository=new ProductRepository(pool);tenant=await repository.createBootstrap({organization:"V02",organization_slug:`v02-${suffix}`,project:"Control",project_slug:"control",environment:"Design",environment_slug:"design",email:`owner-${suffix}@v02.test`,display_name:"Design Partner",password:"Nyst design partner fixture 02!"});other=await repository.createBootstrap({organization:"Other V02",organization_slug:`other-v02-${suffix}`,project:"Other",project_slug:"other",environment:"Other",environment_slug:"other",email:`other-${suffix}@v02.test`,display_name:"Other",password:"Nyst other fixture 02!"});const product=createProductProviderRuntime(store,repository,Ed25519Signer.ephemeral("v02-product"),new MutableClock(),{production:false,enable_development_fake:true});fakeEffect=product.descriptors.find(item=>item.provider==="fake")!.effect_name;fakeSpecVersion=product.descriptors.find(item=>item.provider==="fake")!.spec_version;await repository.configureEffectSpec(tenant,product.descriptors.find(item=>item.provider==="fake")!,true);app=await buildProductServer({repository,effect_specs:product.descriptors,runtime:product.runtime,commit:product.commit,production:false});auth=await login(app,`v02-${suffix}`,`owner-${suffix}@v02.test`,"Nyst design partner fixture 02!")});
  after(async()=>{await app.close();await store.close();await pool.end()});

  it("binds immutable tenant scope, Enforced mode and policy before dispatch",async()=>{const response=await execute(`bound-${suffix}`,runtimeInput("definitely_applied",{repository_id:`bound-${suffix}`}));assert.equal(response.statusCode,200,response.body);const id=String(response.json().action.action_id);const rows=(await pool.query(`SELECT b.environment_mode,s.environment_id,p.retry_mode FROM nyst_action_policy_bindings b JOIN nyst_action_scopes s USING(action_id) JOIN nyst_policy_versions p USING(policy_version_id) WHERE b.action_id=$1`,[id])).rows;assert.equal(rows.length,1);assert.equal(rows[0]?.environment_mode,"enforced");assert.equal(rows[0]?.environment_id,tenant.environment_id);assert.equal(rows[0]?.retry_mode,"never");await assert.rejects(()=>pool.query(`UPDATE nyst_action_policy_bindings SET environment_mode='shadow' WHERE action_id=$1`,[id]),/immutable/)});

  it("isolates Shadow from Enforced execution and uses detected—not prevented—language",async()=>{await repository.setEnvironmentMode(tenant,tenant.user_id,"shadow","Shadow isolation test");const beforeCount=Number((await pool.query(`SELECT count(*)::int count FROM outcome_actions`)).rows[0]?.count);const blocked=await execute(`shadow-block-${suffix}`,runtimeInput("definitely_applied",{repository_id:`shadow-${suffix}`}));assert.equal(blocked.statusCode,409);assert.equal(Number((await pool.query(`SELECT count(*)::int count FROM outcome_actions`)).rows[0]?.count),beforeCount);const shadow=await app.inject({method:"POST",url:"/v1/shadow/evaluations",headers:headers(),payload:{effect:fakeEffect,spec_version:fakeSpecVersion,businessKey:`shadow-${suffix}`,observation:{transport:"ambiguous",authoritative_goal_observed:null,attempted_retry:true,attempted_continuation:true,provider_state:{current_permission:"read",desired_permission:"none",attributed:false}}}});assert.equal(shadow.statusCode,200,shadow.body);assert.equal(shadow.json().assessment.language,"detected");assert.match(shadow.json().assessment.note,/did not prevent/);await repository.setEnvironmentMode(tenant,tenant.user_id,"enforced","Return to enforced test baseline")});

  it("requires approval when the newest conservative policy says so and preserves historical binding",async()=>{const first=await execute(`historical-${suffix}`,runtimeInput("goal_state_preexisting",{repository_id:`history-${suffix}`}));assert.equal(first.statusCode,200);const firstId=String(first.json().action.action_id);const original=String((await pool.query(`SELECT policy_version_id FROM nyst_action_policy_bindings WHERE action_id=$1`,[firstId])).rows[0]?.policy_version_id);await repository.createPolicyVersion(tenant,tenant.user_id,{effect_name:fakeEffect,execution_mode:"approval_required",auto_continuation:false,auto_compensation:false,reconcile_timeout_seconds:120});const denied=await execute(`approval-denied-${suffix}`,runtimeInput("definitely_applied",{repository_id:`deny-${suffix}`}));assert.equal(denied.statusCode,409);const approved=await execute(`approval-ok-${suffix}`,runtimeInput("definitely_applied",{repository_id:`ok-${suffix}`}),true);assert.equal(approved.statusCode,200,approved.body);assert.equal(String((await pool.query(`SELECT policy_version_id FROM nyst_action_policy_bindings WHERE action_id=$1`,[firstId])).rows[0]?.policy_version_id),original)});

  it("deduplicates automatic recovery authorization and serializes workers",async()=>{await repository.createPolicyVersion(tenant,tenant.user_id,{effect_name:fakeEffect,execution_mode:"automatic",auto_continuation:true,auto_compensation:false,reconcile_timeout_seconds:120});const response=await execute(`recovery-${suffix}`,runtimeInput("goal_state_preexisting",{repository_id:`recovery-${suffix}`}));assert.equal(response.statusCode,200,response.body);const body=response.json();const actionId=String(body.action.action_id);const resolutionId=String(body.resolution.resolution_id);const first=await repository.authorizeRecovery(tenant,actionId,resolutionId,"authorized_continuation");const duplicate=await repository.authorizeRecovery(tenant,actionId,resolutionId,"authorized_continuation");assert.equal(first.recovery_execution_id,duplicate.recovery_execution_id);const claims=await Promise.all(Array.from({length:10},()=>repository.claimRecovery({environment_id:tenant.environment_id})));assert.equal(claims.filter(Boolean).length,1);const claim=claims.find(Boolean)!;assert.equal(await repository.completeRecovery(String(claim.recovery_execution_id),String(claim.claim_token),true),true);assert.equal(await repository.completeRecovery(String(claim.recovery_execution_id),String(claim.claim_token),true),false)});

  it("creates one signed webhook event, delivers it once per claim, and persists attempts",async()=>{await repository.configureWebhook(tenant,tenant.user_id,"https://events.example.com/nyst","env:NYST_WEBHOOK_SIGNING_SECRET");const response=await execute(`webhook-${suffix}`,runtimeInput("definitely_applied",{repository_id:`webhook-${suffix}`}));assert.equal(response.statusCode,200,response.body);const body=response.json();await repository.queueDecisionWebhook(tenant,String(body.action.action_id),body.resolution,"effect.resolved");const event=(await pool.query(`SELECT webhook_event_id FROM nyst_webhook_events WHERE action_id=$1 AND event_type='effect.resolved' ORDER BY occurred_at,webhook_event_id LIMIT 1`,[body.action.action_id])).rows[0];assert.ok(event?.webhook_event_id);let received:{body:string;signature:string;timestamp:string;eventId:string}|null=null;const worker=new NystDecisionWebhookWorker(pool,{async resolve(){return "synthetic-webhook-secret-value-00000000"}},async(_url,init)=>{received={body:String(init?.body),signature:String((init?.headers as Record<string,string>)["x-nyst-signature"]),timestamp:String((init?.headers as Record<string,string>)["x-nyst-timestamp"]),eventId:String((init?.headers as Record<string,string>)["x-nyst-event-id"])};return new Response("",{status:204})},30000,async()=>[{address:"93.184.216.34"}],tenant.environment_id);for(let attempt=0;attempt<40;attempt++){await worker.runOne();const deliveredAt=(await pool.query(`SELECT delivered_at FROM nyst_webhook_events WHERE webhook_event_id=$1`,[event.webhook_event_id])).rows[0]?.delivered_at;if(deliveredAt)break}const delivered=received as unknown as {body:string;signature:string;timestamp:string;eventId:string};assert.match(delivered.signature,/^v1=[0-9a-f]{64}$/);assert.match(delivered.body,new RegExp(delivered.eventId));assert.equal(delivered.eventId,event.webhook_event_id);assert.equal(Number((await pool.query(`SELECT count(*)::int count FROM nyst_webhook_attempts WHERE webhook_event_id=$1`,[event.webhook_event_id])).rows[0]?.count),1)});

  it("rejects webhook SSRF targets and cross-tenant ownership",async()=>{for(const target of ["https://127.0.0.1/hook","https://169.254.169.254/hook","http://events.example.com/hook"])await assert.rejects(()=>repository.configureWebhook(tenant,tenant.user_id,target,"env:NYST_WEBHOOK_SIGNING_SECRET"));await assert.rejects(()=>repository.configureWebhook({...tenant,environment_id:other.environment_id},tenant.user_id,"https://events.example.com/hook","env:NYST_WEBHOOK_SIGNING_SECRET"),/different tenant scope/)});

  it("isolates Failure Lab from enforced environments and never uses provider credentials",async()=>{const denied=await app.inject({method:"POST",url:"/v1/failure-lab/runs",headers:headers(),payload:{scenario:"response_lost",effect:fakeEffect,seed:42}});assert.equal(denied.statusCode,500);await repository.setEnvironmentMode(tenant,tenant.user_id,"shadow","Failure Lab isolation");const allowed=await app.inject({method:"POST",url:"/v1/failure-lab/runs",headers:headers(),payload:{scenario:"response_lost",effect:fakeEffect,seed:42}});assert.equal(allowed.statusCode,200,allowed.body);assert.equal(allowed.json().simulated,true);assert.equal(allowed.json().provider_credentials_used,false);await repository.setEnvironmentMode(tenant,tenant.user_id,"enforced","Restore enforced baseline")});

  it("deduplicates Shadow impact metrics by supplied logical record",async()=>{await repository.setEnvironmentMode(tenant,tenant.user_id,"shadow","Metrics test");const observation={transport:"ambiguous" as const,authoritative_goal_observed:null,attempted_retry:true,attempted_continuation:false,provider_state:{current_permission:"read",desired_permission:"none",attributed:false}};await repository.recordShadowEvaluation(tenant,fakeEffect,`metric-${suffix}`,observation,fakeSpecVersion);await repository.recordShadowEvaluation(tenant,fakeEffect,`metric-${suffix}`,observation,fakeSpecVersion);const metrics=await repository.impactMetrics(tenant);assert.equal(metrics.mode,"shadow");assert.ok(Number(metrics.unsafe_retries_detected_shadow)>=1);assert.equal(Number((await pool.query(`SELECT count(*)::int count FROM nyst_shadow_evaluations WHERE environment_id=$1 AND business_key=$2`,[tenant.environment_id,`metric-${suffix}`])).rows[0]?.count),1);await repository.setEnvironmentMode(tenant,tenant.user_id,"enforced","Restore enforced baseline")});

  it("human review offers no force-continue operation",async()=>{const response=await execute(`review-${suffix}`,runtimeInput("transport_timeout",{repository_id:`review-${suffix}`}));assert.equal(response.statusCode,200,response.body);const actionId=String(response.json().action.action_id);const opened=await app.inject({method:"POST",url:`/v1/actions/${actionId}/reviews`,headers:headers(),payload:{reason:"Transport ambiguity requires review"}});assert.equal(opened.statusCode,200,opened.body);const force=await app.inject({method:"POST",url:`/v1/reviews/${opened.json().human_review_id}`,headers:headers(),payload:{operation:"force_continue"}});assert.equal(force.statusCode,400);const acknowledge=await app.inject({method:"POST",url:`/v1/reviews/${opened.json().human_review_id}`,headers:headers(),payload:{operation:"acknowledge"}});assert.equal(acknowledge.statusCode,200)});

  it("requires a session for mode/policy changes and retains tenant isolation",async()=>{const key=await repository.createApiKey(tenant,"mode attack",["actions:read","actions:write"]);const attack=await app.inject({method:"PUT",url:"/v1/environment/mode",headers:{authorization:`Nyst ${key.key}`},payload:{mode:"shadow",reason:"attack"}});assert.equal(attack.statusCode,403);assert.equal((await repository.environmentControl(tenant)).mode,"enforced");assert.equal((await repository.environmentControl(other)).mode,"enforced")});

  it("serves readiness plus the complete design-partner product story",async()=>{assert.equal((await app.inject({method:"GET",url:"/health"})).statusCode,200);assert.equal((await app.inject({method:"GET",url:"/ready"})).statusCode,200);for(const [path,pattern] of [["/",/safety control plane/i],["/policies",/Non-bypassable floor/],["/effect-registry",/Provider semantics/],["/failure-lab",/SIMULATED/],["/integrations",/Connection readiness/],["/reviews",/no force-continue override/i],["/onboarding",/@nyst-ai\/sdk/],["/settings",/Decision webhook/]] as const){const page=await app.inject({method:"GET",url:path,headers:{cookie:auth.cookie}});assert.equal(page.statusCode,200,`${path}: ${page.body}`);assert.match(page.body,pattern)}});

  function headers(){return{cookie:auth.cookie,"x-nyst-csrf":auth.csrf}}function execute(businessKey:string,input:unknown,approved=false){return app.inject({method:"POST",url:"/v1/actions",headers:headers(),payload:{effect:fakeEffect,businessKey,input,approved}})}
});
async function login(app:Awaited<ReturnType<typeof buildProductServer>>,organization:string,email:string,password:string){const response=await app.inject({method:"POST",url:"/v1/auth/login",payload:{organization,email,password}});assert.equal(response.statusCode,200,response.body);const pair=String(response.headers["set-cookie"]).split(";",1)[0]!;return{cookie:pair,session:pair.split("=",2)[1]!,csrf:String(response.json().csrf)}}
