import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { assessShadow,constrainDecision,signWebhook,validateWebhookTarget,verifyWebhook } from "../src/product/controlPlane.js";
import { runFailureLabEngine } from "../src/product/failureLabEngine.js";
import { NystClient } from "../src/product/sdk.js";

describe("Nyst v0.2 product safety controls",()=>{
  it("describes Shadow findings as detected counterfactuals, never prevented effects",()=>{const value=assessShadow({transport:"ambiguous",authoritative_goal_observed:null,attempted_retry:true,attempted_continuation:true});assert.equal(value.language,"detected");assert.equal(value.retry_would_have_been_blocked,true);assert.match(value.note,/did not prevent/);assert.doesNotMatch(JSON.stringify(value),/prevented/)});
  it("customer policy can only reduce runtime authority",()=>{const decision={decision_version:1,primary:"continue",retry:"allowed",continuation:"allowed",recovery:"compensate",reason_code:"TEST",explanation:"runtime decision",policy_version:"runtime",spec_version:"spec"} as const;const constrained=constrainDecision(decision,{policy_version_id:"p",execution_mode:"automatic",retry_mode:"never",auto_continuation:false,auto_compensation:false,reconcile_timeout_seconds:300});assert.equal(constrained.retry,"forbidden");assert.equal(constrained.continuation,"blocked");assert.equal(constrained.primary,"hold");assert.equal(constrained.recovery,"escalate")});
  it("rejects internal, credentialed, non-HTTPS and private webhook destinations",()=>{for(const value of ["http://example.com","https://user:pass@example.com","https://localhost/hook","https://127.0.0.1/hook","https://10.0.0.2/hook","https://169.254.169.254/latest","https://service.internal/hook","https://[::1]/hook"])assert.throws(()=>validateWebhookTarget(value));assert.equal(validateWebhookTarget("https://events.example.com/nyst").hostname,"events.example.com")});
  it("signs webhook bytes and enforces a bounded replay window",()=>{const secret="synthetic-webhook-signing-secret-000000";const timestamp=new Date().toISOString();const body=JSON.stringify({event_id:"fixture"});const signature=signWebhook(secret,timestamp,body);assert.equal(verifyWebhook(secret,timestamp,body,signature),true);assert.equal(verifyWebhook(secret,timestamp,body+"x",signature),false);assert.equal(verifyWebhook(secret,new Date(Date.now()-360000).toISOString(),body,signWebhook(secret,new Date(Date.now()-360000).toISOString(),body)),false)});
  it("Failure Lab outputs are engine-derived, explicitly simulated and credential-free",async()=>{const first=await runFailureLabEngine("response_lost","fake.repository_permission_change",42);const second=await runFailureLabEngine("response_lost","fake.repository_permission_change",42);assert.equal(first.final_effect_state,second.final_effect_state);assert.equal(first.provider_mutations,second.provider_mutations);assert.equal(first.simulated,true);assert.equal(first.provider_credentials_used,false);assert.equal(first.duplicate_consequence_avoided_in_simulation,true)});
  it("SDK preserves callable actions while adding actions.execute and Shadow evaluation",async()=>{const seen:Array<{url:string;body:string}>=[];const client=new NystClient({baseUrl:"https://nyst.test",apiKey:"nyst_fixture.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL",fetch:async(input,init)=>{seen.push({url:String(input),body:String(init?.body??"")});return new Response("{}",{status:200,headers:{"content-type":"application/json"}})}});await client.actions();await client.actions.execute({effect:"github.repository_permission_change",businessKey:"fixture",input:{}});await client.shadow.evaluate({effect:"github.repository_permission_change",businessKey:"fixture",observation:{transport:"ambiguous",authoritative_goal_observed:null,attempted_retry:true,attempted_continuation:false}});assert.match(seen[1]!.url,/\/v1\/actions$/);assert.match(seen[2]!.url,/\/v1\/shadow\/evaluations$/)});
});
