import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, describe, it } from "node:test";
import { Ed25519Signer } from "../src/core/signing.js";
import { EMPTY_CONTEXT } from "../src/model/metadata.js";
import { ProductRepository, type ProductDb } from "../src/product/productRepository.js";
import { createProductProviderRuntime } from "../src/product/providerRuntimeFactory.js";
import { NystRecoveryWorker, RecoveryExecutorRegistry } from "../src/product/recoveryWorker.js";
import { NystReobservationWorker } from "../src/product/reobservationWorker.js";
import { InMemoryOperationalMetrics, NystReconciliationScheduler } from "../src/product/scheduler.js";
import { buildProductServer } from "../src/product/server.js";
import type { TenantScope } from "../src/product/types.js";
import { NystDecisionWebhookWorker } from "../src/product/webhookWorker.js";
import { createPostgresStore } from "../src/store/postgresStore.js";
import { MutableClock } from "./githubHelpers.js";
import { runtimeInput } from "./runtimeHelpers.js";

const databaseUrl=process.env.DATABASE_URL;
describe("Nyst v0.2.1 PostgreSQL correctness controls",{skip:databaseUrl?false:"DATABASE_URL not set — PostgreSQL is required"},()=>{
  let pool:ProductDb&{end():Promise<void>};let store:Awaited<ReturnType<typeof createPostgresStore>>;let repository:ProductRepository;let tenant:TenantScope&{user_id:string};let runtime:ReturnType<typeof createProductProviderRuntime>["runtime"];let descriptors:ReturnType<typeof createProductProviderRuntime>["descriptors"];let effect:string;const suffix=randomUUID().slice(0,8);
  before(async()=>{const pg=await import("pg") as unknown as{default:{Pool:new(options:{connectionString:string})=>ProductDb&{end():Promise<void>}}};pool=new pg.default.Pool({connectionString:databaseUrl!});store=await createPostgresStore(databaseUrl!);repository=new ProductRepository(pool);tenant=await repository.createBootstrap({organization:"V021",organization_slug:`v021-${suffix}`,project:"Correctness",project_slug:"correctness",environment:"Adversarial",environment_slug:"adversarial",email:`owner-${suffix}@v021.test`,display_name:"V021 Owner",password:"Nyst v021 correctness fixture 47!"});const product=createProductProviderRuntime(store,repository,Ed25519Signer.ephemeral("v021-pg"),new MutableClock(),{production:false,enable_development_fake:true});runtime=product.runtime;descriptors=product.descriptors;effect=descriptors.find(item=>item.provider==="fake")!.effect_name;await repository.configureEffectSpec(tenant,descriptors.find(item=>item.effect_name===effect)!,true)});
  after(async()=>{await store.close();await pool.end()});

  it("enforces policy-version and environment-mode audit immutability in PostgreSQL",async()=>{const policy=await repository.createPolicyVersion(tenant,tenant.user_id,{effect_name:effect,execution_mode:"automatic",auto_continuation:true,auto_compensation:false,reconcile_timeout_seconds:30});await assert.rejects(()=>pool.query(`UPDATE nyst_policy_versions SET auto_continuation=false WHERE policy_version_id=$1`,[policy.policy_version_id]),/immutable/);await assert.rejects(()=>pool.query(`DELETE FROM nyst_policy_versions WHERE policy_version_id=$1`,[policy.policy_version_id]),/immutable/);await repository.setEnvironmentMode(tenant,tenant.user_id,"shadow","immutability proof");await repository.setEnvironmentMode(tenant,tenant.user_id,"enforced","restore enforced");const audit=(await pool.query(`SELECT audit_id FROM nyst_environment_mode_audit WHERE environment_id=$1 ORDER BY changed_at DESC LIMIT 1`,[tenant.environment_id])).rows[0]!;await assert.rejects(()=>pool.query(`UPDATE nyst_environment_mode_audit SET reason='rewrite' WHERE audit_id=$1`,[audit.audit_id]),/immutable/);await assert.rejects(()=>pool.query(`DELETE FROM nyst_environment_mode_audit WHERE audit_id=$1`,[audit.audit_id]),/immutable/)});

  it("turns the bound reconciliation timeout into durable escalation without changing EffectState",async()=>{const result=await runtime.commit(effect,`${tenant.environment_id}:deadline-${suffix}`,runtimeInput("eventual_consistency",{repository_id:`deadline-${suffix}`}),EMPTY_CONTEXT,{establish_dispatch_eligibility:action=>repository.scopeAction(tenant,action.action_id,`deadline-${suffix}`)});assert.equal(result.resolution.effect.state,"pending");await repository.recordResolutionTransition(result.action.action_id,result.resolution,"action_commit");const count=await repository.escalateOverdueReconciliations("2100-01-01T00:00:00.000Z");assert.ok(count>=1);const latest=(await store.resolutions.latestForAction(result.action.action_id))!;assert.equal(latest.effect.state,"pending");assert.equal((await pool.query(`SELECT count(*)::int count FROM nyst_human_reviews WHERE action_id=$1`,[result.action.action_id])).rows[0]?.count,1);assert.equal((await pool.query(`SELECT count(*)::int count FROM nyst_reconciliation_jobs WHERE action_id=$1`,[result.action.action_id])).rows[0]?.count,0)});

  it("serializes 2/10 recovery workers and never re-executes after an ambiguous executor failure",async()=>{await repository.createPolicyVersion(tenant,tenant.user_id,{effect_name:effect,execution_mode:"automatic",auto_continuation:true,auto_compensation:false,reconcile_timeout_seconds:300});const first=await runtime.commit(effect,`${tenant.environment_id}:recover-ok-${suffix}`,runtimeInput("definitely_applied",{repository_id:`recover-ok-${suffix}`}),EMPTY_CONTEXT,{establish_dispatch_eligibility:action=>repository.scopeAction(tenant,action.action_id,`recover-ok-${suffix}`)});await repository.recordResolutionTransition(first.action.action_id,first.resolution,"action_commit");await repository.authorizeRecovery(tenant,first.action.action_id,first.resolution.resolution_id,"authorized_continuation");let successfulCalls=0;const registry=new RecoveryExecutorRegistry();registry.register(effect,"authorized_continuation",async()=>{successfulCalls++;return{outcome:"completed"}});const workers=Array.from({length:10},()=>new NystRecoveryWorker(repository,registry));await Promise.all(workers.map(worker=>worker.runOne()));assert.equal(successfulCalls,1);assert.equal((await pool.query(`SELECT status FROM nyst_recovery_executions WHERE action_id=$1`,[first.action.action_id])).rows[0]?.status,"completed");
    const second=await runtime.commit(effect,`${tenant.environment_id}:recover-loss-${suffix}`,runtimeInput("definitely_applied",{repository_id:`recover-loss-${suffix}`}),EMPTY_CONTEXT,{establish_dispatch_eligibility:action=>repository.scopeAction(tenant,action.action_id,`recover-loss-${suffix}`)});await repository.recordResolutionTransition(second.action.action_id,second.resolution,"action_commit");await repository.authorizeRecovery(tenant,second.action.action_id,second.resolution.resolution_id,"authorized_continuation");let ambiguousCalls=0;const failingRegistry=new RecoveryExecutorRegistry();failingRegistry.register(effect,"authorized_continuation",async()=>{ambiguousCalls++;throw new Error("response lost after downstream consequence")});const failingWorkers=Array.from({length:10},()=>new NystRecoveryWorker(repository,failingRegistry));await Promise.all(failingWorkers.map(worker=>worker.runOne()));await Promise.all(failingWorkers.slice(0,2).map(worker=>worker.runOne()));assert.equal(ambiguousCalls,1);const failed=(await pool.query(`SELECT status,result FROM nyst_recovery_executions WHERE action_id=$1`,[second.action.action_id])).rows[0]!;assert.equal(failed.status,"failed");assert.equal((failed.result as Record<string,unknown>).error_code,"Error")});

  it("runs human-requested re-observation through an observation-only worker exactly once",async()=>{const result=await runtime.commit(effect,`${tenant.environment_id}:review-${suffix}`,runtimeInput("transport_timeout",{repository_id:`review-${suffix}`}),EMPTY_CONTEXT,{establish_dispatch_eligibility:action=>repository.scopeAction(tenant,action.action_id,`review-${suffix}`)});await repository.recordResolutionTransition(result.action.action_id,result.resolution,"action_commit");const review=await repository.openHumanReview(tenant,result.action.action_id,"Ambiguous transport");await repository.updateHumanReview(tenant,tenant.user_id,String(review.human_review_id),"request_reobservation");await assert.rejects(()=>repository.updateHumanReview(tenant,tenant.user_id,String(review.human_review_id),"request_reobservation"),/already handled/);let observations=0;const worker=new NystReobservationWorker(repository,{async reconcile(actionId){observations++;return runtime.reconcile(actionId)}});assert.equal((await Promise.all([worker.runOne(),worker.runOne()])).filter(Boolean).length,1);assert.equal(observations,1);assert.equal((await pool.query(`SELECT status FROM nyst_reobservation_jobs WHERE human_review_id=$1`,[review.human_review_id])).rows[0]?.status,"completed")});

  it("records real transition origins and scoped metrics without duplicate inflation",async()=>{const result=await runtime.commit(effect,`${tenant.environment_id}:metrics-${suffix}`,runtimeInput("response_lost_after_effect",{repository_id:`metrics-${suffix}`}),EMPTY_CONTEXT,{establish_dispatch_eligibility:action=>repository.scopeAction(tenant,action.action_id,`metrics-${suffix}`)});assert.equal(await repository.recordResolutionTransition(result.action.action_id,result.resolution,"action_commit"),true);assert.equal(await repository.recordResolutionTransition(result.action.action_id,result.resolution,"action_commit"),false);const next=await runtime.reconcile(result.action.action_id);assert.equal(await repository.recordResolutionTransition(result.action.action_id,next,"scheduler"),true);const metrics=await repository.impactMetrics(tenant);assert.ok(Number(metrics.consequential_actions)>=1);assert.ok(Number(metrics.ambiguous_executions)>=1);assert.ok(Number(metrics.unsafe_retries_prevented_enforced)>=1);const origins=(await pool.query(`SELECT origin FROM nyst_resolution_transitions WHERE action_id=$1 ORDER BY resolution_sequence`,[result.action.action_id])).rows.map(row=>row.origin);assert.deepEqual(origins,["action_commit","scheduler"])});

  it("queues a real-resolution test event and blocks DNS rebinding before delivery",async()=>{
    await repository.configureWebhook(tenant,tenant.user_id,"https://events.example.com/nyst","env:NYST_WEBHOOK_SECRET");
    const queued=await repository.queueWebhookTest(tenant);assert.equal(queued.event_type,"webhook.test");
    const event=(await pool.query(`SELECT payload,event_schema_version FROM nyst_webhook_events WHERE webhook_event_id=$1`,[queued.webhook_event_id])).rows[0]!;
    const payload=event.payload as Record<string,unknown>;assert.equal(event.event_schema_version,1);assert.equal(payload.event_type,"webhook.test");assert.ok(typeof payload.effect_state==="string");assert.ok(typeof payload.control==="object");assert.match(String(payload.receipt_ref),/^\/v1\/actions\//);
    let requests=0;const worker=new NystDecisionWebhookWorker(pool,{async resolve(){return"synthetic-v021-webhook-secret-000000000"}},async()=>{requests++;return new Response("",{status:204})},30_000,async()=>[{address:"93.184.216.34"},{address:"127.0.0.1"}]);
    let attempt:Record<string,unknown>|undefined;
    for(let index=0;index<100&&!attempt;index++){await worker.runOne();attempt=(await pool.query(`SELECT error_code FROM nyst_webhook_attempts WHERE webhook_event_id=$1`,[queued.webhook_event_id])).rows[0]}
    assert.equal(requests,0);assert.equal(attempt?.error_code,"webhook_target_not_public");
  });

  it("does not follow a webhook redirect and persists the bounded failure",async()=>{const action=(await pool.query(`SELECT action_id FROM nyst_action_scopes WHERE environment_id=$1 ORDER BY created_at DESC LIMIT 1`,[tenant.environment_id])).rows[0]!;const resolution=await runtime.reconcile(String(action.action_id));await repository.recordResolutionTransition(String(action.action_id),resolution,"manual_reconcile");let requests=0;const worker=new NystDecisionWebhookWorker(pool,{async resolve(){return"synthetic-v021-webhook-secret-000000000"}},async(_input,init)=>{requests++;assert.equal(init?.redirect,"error");return new Response("",{status:302,headers:{location:"https://127.0.0.1/"}})},30_000,async()=>[{address:"93.184.216.34"}]);assert.equal(await worker.runOne(),true);assert.equal(requests,1);const attempt=(await pool.query(`SELECT response_status,error_code FROM nyst_webhook_attempts ORDER BY attempted_at DESC LIMIT 1`)).rows[0]!;assert.equal(attempt.response_status,302);assert.equal(attempt.error_code,"webhook_http_302")});

  it("distinguishes available, enabled, and consequence-ready EffectSpecs and performs no mutation in credential readiness",async()=>{const initial=await repository.effectSpecStatuses(tenant,descriptors,false);const fake=initial.find(item=>item.effect_name===effect)!;const github=initial.find(item=>item.provider==="github")!;assert.equal(fake.status,"ready");assert.equal(github.status,"available");const githubDescriptor=descriptors.find(item=>item.provider==="github")!;await repository.configureIntegration(tenant,"github","env:NYST_GITHUB_TOKEN");await repository.configureEffectSpec(tenant,githubDescriptor,true);const configured=(await repository.effectSpecStatuses(tenant,descriptors,false)).find(item=>item.provider==="github")!;assert.equal(configured.enabled,true);assert.equal(configured.ready,true);const readiness=await repository.testIntegration(tenant,"github",{NYST_GITHUB_TOKEN:"synthetic-readiness-only"});assert.equal(readiness.status,"credential_ready");assert.equal(readiness.read_only_preflight_performed,false);assert.equal(readiness.provider_mutation_performed,false)});

  it("disables future webhook events without rewriting history and exposes attempt status",async()=>{const before=(await pool.query(`SELECT count(*)::int count FROM nyst_webhook_events e JOIN nyst_webhook_endpoints w USING(webhook_endpoint_id) WHERE w.environment_id=$1`,[tenant.environment_id])).rows[0]!.count;await repository.setWebhookEnabled(tenant,tenant.user_id,false);const status=(await repository.webhookStatus(tenant))[0]!;assert.equal(status.enabled,false);assert.ok(Number(status.delivery_attempt_count)>=1);await assert.rejects(()=>repository.queueWebhookTest(tenant),/enabled endpoint/);const after=(await pool.query(`SELECT count(*)::int count FROM nyst_webhook_events e JOIN nyst_webhook_endpoints w USING(webhook_endpoint_id) WHERE w.environment_id=$1`,[tenant.environment_id])).rows[0]!.count;assert.equal(after,before);await repository.setWebhookEnabled(tenant,tenant.user_id,true)});

  it("derives onboarding completion from real persisted operations and permits only SDK attestation",async()=>{const before=await repository.onboardingProgress(tenant);assert.equal(Array.isArray(before.completed),true);await repository.createApiKey(tenant,"onboarding",["actions:read","actions:write","receipts:read"]);await repository.attestSdkInstalled(tenant);const after=await repository.onboardingProgress(tenant);const completed=after.completed as boolean[];assert.equal(completed.slice(0,7).every(Boolean),true);assert.ok(Number(after.stage)>=7);assert.equal((await repository.apiKeys(tenant)).some(key=>key.name==="onboarding"),true)});

  it("rate limiting returns before a consequence-capable handler",async()=>{let consequences=0;const descriptor={effect_name:effect,spec_version:"fake.repository_permission_change/1.0.0",provider:"fake",supported_topology:"test"};const app=await buildProductServer({repository,effect_specs:[descriptor],commit:async()=>{consequences++;throw new Error("must not execute")}});for(let index=0;index<300;index++)await app.inject({method:"GET",url:"/health"});const blocked=await app.inject({method:"POST",url:"/v1/actions",payload:{}});assert.equal(blocked.statusCode,429);assert.equal(consequences,0);await app.close()});

  it("scheduler transition control is observation-only and policy deadline escalation is synchronized",async()=>{const scheduler=new NystReconciliationScheduler(pool,runtime,new InMemoryOperationalMetrics(),30_000,repository);await scheduler.sync();assert.equal(typeof await scheduler.runOne(),"boolean")});
});
