/** Dedicated Nyst reconciliation and outbound-decision worker. */
import { Ed25519Signer } from "../dist/src/core/signing.js";
import { LocalSystemClock } from "../dist/src/core/clock.js";
import { ProductRepository } from "../dist/src/product/productRepository.js";
import { createProductProviderRuntime } from "../dist/src/product/providerRuntimeFactory.js";
import { InMemoryOperationalMetrics,NystReconciliationScheduler } from "../dist/src/product/scheduler.js";
import { NystDecisionWebhookWorker } from "../dist/src/product/webhookWorker.js";
import { NystRecoveryWorker,RecoveryExecutorRegistry } from "../dist/src/product/recoveryWorker.js";
import { NystReobservationWorker } from "../dist/src/product/reobservationWorker.js";
import { OKTA_EFFECT_NAME } from "../dist/src/providers/okta/types.js";
import { createPostgresStore } from "../dist/src/store/postgresStore.js";
const databaseUrl=process.env.DATABASE_URL;if(!databaseUrl)throw new Error("DATABASE_URL is required");const signer=Ed25519Signer.fromEnv();const clock=new LocalSystemClock();const store=await createPostgresStore(databaseUrl);const pg=await import("pg");const pool=new pg.default.Pool({connectionString:databaseUrl});const repository=new ProductRepository(pool);const product=createProductProviderRuntime(store,repository,signer,clock,{production:process.env.NODE_ENV==="production"});const metrics=new InMemoryOperationalMetrics();const scheduler=new NystReconciliationScheduler(pool,product.runtime,metrics,30_000,repository);const webhooks=new NystDecisionWebhookWorker(pool);const executors=new RecoveryExecutorRegistry();for(const descriptor of product.descriptors)executors.register(descriptor.effect_name,"supported_compensation",async claim=>({outcome:"completed",resolution:await product.runtime.compensate(claim.action_id)}));executors.register(OKTA_EFFECT_NAME,"authorized_continuation",async claim=>{const intent=await repository.offboardingIntentForOktaAction({organization_id:claim.organization_id,project_id:claim.project_id,environment_id:claim.environment_id},claim.action_id);if(!intent)throw new Error("Unsupported continuation: action is not the Okta step of a scoped offboarding run");const {created_at:_created,...input}=intent;const view=await product.offboarding.execute(input as never);if(view.status!=="complete")throw new Error(`Offboarding continuation did not complete: ${view.status}`);return {outcome:"completed",provider_reference:view.run.github_action_id??undefined}});const recovery=new NystRecoveryWorker(repository,executors);const reobservation=new NystReobservationWorker(repository,product.runtime);let stopping=false;const run=async()=>{if(stopping)return;try{await scheduler.sync();await Promise.all([scheduler.runOne(),webhooks.runOne(),recovery.runOne(),reobservation.runOne()])}catch{metrics.increment("worker_errors")}};const timer=setInterval(()=>void run(),1000);console.log(JSON.stringify({type:"service_started",service:"nyst-worker",version:"0.2.1"}));for(const signal of ["SIGINT","SIGTERM"] as const)process.on(signal,()=>{stopping=true;clearInterval(timer);void Promise.all([store.close(),pool.end()]).then(()=>process.exit(0))});
