import { currentExplanation, latestResolution, resolutionHistory } from "./actionPresentation.js";
import { sanitizeForProduct } from "./sanitize.js";
import type { CanonicalMetrics, InterventionSummary } from "./canonicalMetrics.js";

const nav=[["/","Overview"],["/actions","Actions"],["/policies","Policies"],["/effect-registry","Effect Registry"],["/failure-lab","Failure Lab"],["/integrations","Integrations"],["/reviews","Human Review"],["/settings","Settings"]] as const;

export function loginPage():string{return page("Login",`<main class="login"><section class="login-brand"><div class="brand-lockup"><img src="/brand/nyst-wordmark.png" alt="Nyst"></div><p class="eyebrow">Safety control plane</p><h1>Know what happened.<br>Control what happens next.</h1><p>Nyst sits between autonomous software and the systems it changes.</p></section><section class="panel login-card"><h2>Sign in to Nyst</h2><form id="login-form"><label>Organization<input name="organization" autocomplete="organization" required></label><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button>Continue</button><p id="login-error" role="alert"></p></form></section></main>`,false,"/assets/login.js")}

/**
 * Overview.
 *
 * Typed against CanonicalMetrics, not `Record<string, unknown>`. That is the
 * structural half of the 1A fix: a field-name drift between the metric service
 * and this card is now a compile error instead of a silent zero.
 */
export function overviewPage(data:CanonicalMetrics):string{const mode=data.mode;const shadow=mode==="shadow";const cards:ReadonlyArray<readonly [string,number,string]>=[
  ["Consequential actions",data.consequential_actions,"Durable logical actions in this environment"],
  ["Ambiguous executions",data.ambiguous_executions,"Distinct incidents, not repeated observations"],
  shadow
    ? ["Unsafe retries detected",data.unsafe_retries_detected_shadow,"Would-have-blocked; Nyst did not control execution"] as const
    : ["Unsafe retries prevented",data.unsafe_retries_prevented_enforced,"Blocked by Nyst while controlling the action"] as const,
  shadow
    ? ["Unsafe continuations detected",data.unsafe_continuations_detected_shadow,"Would-have-held; Nyst did not control execution"] as const
    : ["Unsafe continuations prevented",data.unsafe_continuations_prevented_enforced,"Held by Nyst while controlling the action"] as const,
  ["Automatically resolved",data.auto_resolved,"Authorized recovery executions completed"],
  ["Human escalations",data.human_escalations,"Actions requiring bounded review"],
];return shell("Overview",`<header class="hero"><div><p class="eyebrow">CONNECT → ROUTE → CONTROL → RECOVER → PROVE</p><h1>The safety control plane for consequential actions.</h1><p class="lede">Nyst determines what actually happened after autonomous software changes production—and decides what is safe next.</p></div><span class="mode ${mode}">${escape(mode.toUpperCase())}</span></header><section class="metric-grid">${cards.map(([name,value,note])=>`<article class="metric"><span>${escape(name)}</span><strong>${escape(String(value))}</strong><small>${escape(note)}</small></article>`).join("")}</section><section class="value-flow"><article><b>01</b><span>Agent</span><small>declares durable intent</small></article><i>→</i><article class="nyst-node"><img src="/brand/nyst-mark.png" alt=""><span>Nyst</span><small>controls ambiguity</small></article><i>→</i><article><b>03</b><span>Provider</span><small>external consequence</small></article></section><section><div class="section-head"><div><p class="eyebrow">Durable records, never inferred from current state</p><h2>Recent interventions</h2></div><a href="/actions">Open action ledger →</a></div>${interventionTable(data.recent_interventions)}</section>`)}

/** Recent Interventions renders durable intervention records only. */
function interventionTable(items:readonly InterventionSummary[]):string{
  if(!items.length)return `<p class="empty">No interventions have been recorded in this environment yet.</p>`;
  return `<div class="table-scroll"><table><thead><tr><th scope="col">Intervention</th><th scope="col">Effect</th><th scope="col">Agent</th><th scope="col">Mode</th><th scope="col">When</th></tr></thead><tbody>${items.map(item=>`<tr><td><strong>${escape(INTERVENTION_LABELS[item.kind]??item.kind)}</strong><br><small>${escape(item.summary)}</small></td><td>${escape(item.effect_name)}</td><td>${escape(item.agent_name??"unattributed")}</td><td><span class="mode ${escape(item.mode)}">${escape(item.mode)}</span></td><td>${escape(item.occurred_at)}</td></tr>`).join("")}</tbody></table></div>`;
}

const INTERVENTION_LABELS:Readonly<Record<string,string>>={
  retry_blocked:"BLOCKED RETRY",continuation_blocked:"HELD CONTINUATION",auto_resolved:"AUTO-RESOLVED",
  human_review_opened:"HUMAN REVIEW",shadow_retry_would_have_been_blocked:"SHADOW WOULD-HAVE-BLOCKED RETRY",
  shadow_continuation_would_have_been_blocked:"SHADOW WOULD-HAVE-HELD CONTINUATION",
  blast_radius_hold:"BLAST RADIUS HOLD",freeze_blocked:"FROZEN",recovery_needs_review:"RECOVERY NEEDS REVIEW",
};


export function actionsPage(actions:Record<string,unknown>[],title="Actions",filters:Record<string,unknown>={}):string{return shell(title,`<header><p class="eyebrow">Consequential action ledger</p><h1>${escape(title)}</h1><p class="lede">One logical identity. One consequence boundary. Evidence-bounded truth.</p></header>${title==="Actions"?filterForm(filters):""}${actionTable(actions)}`)}

export function actionPage(action:Record<string,unknown>,evidence:Record<string,unknown>[],resolutions:Record<string,unknown>[]):string{const current=latestResolution(resolutions);const history=resolutionHistory(resolutions);const explanation=current?currentExplanation(action,evidence,current):null;const therefore=explanation?.therefore;const runtime=record(action.runtime??action);return shell("Action detail",`<header class="action-hero"><div><p class="eyebrow">${escape(String(action.effect_name))}</p><h1>${escape(String(action.business_key))}</h1><p class="mono copy-id">${escape(String(action.action_id))}</p></div><div class="decision-lockup"><span class="pill ${stateClass(current?.effect_state)}">${escape(String(current?.effect_state??"investigating"))}</span><strong>${escape(String(current?.primary_directive??"investigate").replaceAll("_"," ").toUpperCase())}</strong></div></header><section class="detail-grid facts"><article><span>Environment mode</span><strong>${escape(String(action.environment_mode??"enforced").toUpperCase())}</strong></article><article><span>Provider</span><strong>${escape(String(record(action.dispatch_plan).provider??String(action.effect_name).split(".")[0]))}</strong></article><article><span>Created</span><strong>${escape(shortDate(action.created_at))} UTC</strong></article><article><span>Resolution sequence</span><strong>${escape(String(current?.resolution_sequence??"—"))}</strong></article></section><section class="decision-explanation"><p class="eyebrow">Why did Nyst decide this?</p><h2>${escape(String(explanation?.decision??"investigate").replaceAll("_"," ").toUpperCase())}</h2><div class="explanation-grid"><div><h3>Cited active evidence</h3><ul class="check-list">${(explanation?.facts??[]).map(f=>`<li><span>✓</span><div><strong>${escape(f.fact)}</strong><small>${escape(f.source)} · ${escape(f.strength)} · ${escape(f.attribution)}</small></div></li>`).join("")||"<li><span>○</span><div><strong>No active cited evidence supports a stronger claim</strong><small>Nyst will not infer truth from unrelated or superseded history.</small></div></li>"}</ul>${explanation?.attribution_note?`<p class="attribution-note">${escape(explanation.attribution_note)}</p>`:""}</div><div class="therefore"><h3>Therefore</h3><dl><dt>Retry</dt><dd>${escape(String(therefore?.retry??"unknown"))}</dd><dt>Continuation</dt><dd>${escape(String(therefore?.continuation??"blocked"))}</dd><dt>Recovery</dt><dd>${escape(String(therefore?.recovery??"none"))}</dd></dl></div></div></section><section><div class="section-head"><div><p class="eyebrow">Traceable history</p><h2>Evidence timeline</h2></div><span>${evidence.length} durable records</span></div>${evidenceTimeline(action,evidence,runtime)}</section><section><h2>ControlDecision history</h2>${resolutionTable(history)}</section><section><details><summary>Advanced structured evidence</summary>${json(evidence)}</details></section>`)}

export function policiesPage(items:Record<string,unknown>[]):string{return shell("Policies",`<header><p class="eyebrow">Authority-reducing controls</p><h1>Policies</h1><p class="lede">Policies can make Nyst more conservative. They can never authorize a forbidden retry, blocked continuation, unsupported compensation, or unsupported certainty.</p></header><section class="policy-banner"><strong>Non-bypassable floor</strong><span>EffectSpec + runtime safety semantics always win.</span></section><section class="panel"><h2>Create an immutable policy version</h2><form id="policy-form" class="control-form"><label>Effect (blank = environment default)<input name="effect_name" maxlength="200" placeholder="github.repository_permission_change"></label><label>Execution<select name="execution_mode"><option value="automatic">Automatic within safe decision</option><option value="approval_required">Human approval required</option></select></label><label><input name="auto_continuation" type="checkbox"> Allow automatic continuation when runtime allows</label><label><input name="auto_compensation" type="checkbox"> Allow supported automatic compensation</label><label>Escalate after (seconds)<input name="reconcile_timeout_seconds" type="number" min="30" max="86400" value="300" required></label><button>Create policy version</button><p class="form-status" role="status"></p></form></section><section><h2>Immutable version history</h2><div class="card-grid">${items.map(p=>`<article class="panel"><div class="provider"><h2>${escape(String(p.effect_name??"Environment default"))}</h2><span class="pill neutral">v${escape(String(p.version))}</span></div><dl class="settings-list"><dt>Execution</dt><dd>${escape(String(p.execution_mode))}</dd><dt>Ambiguous retry</dt><dd>never</dd><dt>Automatic continuation</dt><dd>${yes(p.auto_continuation)}</dd><dt>Automatic compensation</dt><dd>${yes(p.auto_compensation)}</dd><dt>Escalate after</dt><dd>${escape(String(p.reconcile_timeout_seconds))}s</dd></dl></article>`).join("")}</div></section>`)}

export function effectRegistryPage(items:Record<string,unknown>[]):string{return shell("Effect Registry",`<header><p class="eyebrow">Provider semantics, not HTTP wrappers</p><h1>Effect Registry</h1><p class="lede">Available, enabled and ready are distinct. Every effect pins identity, observation, attribution, ambiguity, retry and continuation semantics.</p></header><section class="registry-grid">${items.map(item=>`<article class="panel registry-card"><div class="provider"><div><span class="provider-icon">${escape(String(item.provider).slice(0,1).toUpperCase())}</span><h2>${escape(String(item.effect_name))}</h2></div><span class="pill ${item.ready?"good":item.enabled?"warn":"neutral"}">${escape(String(item.status??"available").replaceAll("_"," "))}</span></div><p>${escape(String(item.supported_topology??"Pinned provider topology"))}</p><dl class="settings-list"><dt>Registered</dt><dd>${item.available?"Available":"Unavailable"}</dd><dt>Environment</dt><dd>${item.enabled?"Enabled":"Disabled"}</dd><dt>Consequence ready</dt><dd>${item.ready?"Ready":"Blocked"}</dd><dt>Version</dt><dd>${escape(String(item.spec_version))}</dd><dt>Stable identity</dt><dd>EffectSpec-defined semantic key</dd><dt>Observation</dt><dd>Independent authoritative read-back</dd><dt>Attribution</dt><dd>Only when provider evidence supports it</dd><dt>Ambiguous retry</dt><dd>Fail closed</dd></dl><div class="button-row"><button class="secondary" data-effect-toggle="${escape(String(item.effect_name))}" data-enabled="${item.enabled?"false":"true"}">${item.enabled?"Disable in environment":"Enable in environment"}</button></div><p class="form-status" role="status"></p></article>`).join("")}</section>`)}

export function failureLabPage(runs:Record<string,unknown>[],control:Record<string,unknown>):string{return shell("Failure Lab",`<header class="hero"><div><p class="eyebrow">Real engine · deterministic simulation</p><h1>See Nyst control ambiguity.</h1><p class="lede">Each run executes the production NystRuntime against the credential-free fake EffectSpec. Final state and control are derived from persisted simulation evidence.</p></div><span class="mode demo">SIMULATED</span></header><section class="lab-flow"><article>Agent</article><i>↓</i><article class="nyst-node"><img src="/brand/nyst-mark.png" alt="">Nyst</article><i>↓</i><article>Provider</article></section><section class="scenario-grid">${["response_lost","timeout_before_send","delayed_observation","reconcile_rate_limit","duplicate_caller","process_crash","offboarding_demo"].map(s=>`<button class="scenario" data-scenario="${s}"><strong>${escape(s.replaceAll("_"," "))}</strong><small>Run engine simulation</small></button>`).join("")}</section><section><h2>Recent simulation runs</h2>${runs.length?runs.map(run=>{const result=record(run.result);const controlResult=record(result.control);return `<article class="panel lab-result"><div class="provider"><strong>${escape(String(run.scenario).replaceAll("_"," "))}</strong><span class="pill warn">SIMULATED · NO CREDENTIALS</span></div><dl class="settings-list"><dt>EffectState</dt><dd>${escape(String(result.final_effect_state))}</dd><dt>Control</dt><dd>${escape(String(controlResult.primary))} · retry ${escape(String(controlResult.retry))}</dd><dt>Provider mutations</dt><dd>${escape(String(result.provider_mutations))}</dd><dt>Signature</dt><dd>${result.signature_valid?"valid":"invalid"}</dd></dl><div class="comparison"><p><strong>What naive software might do</strong><br>${escape(String(result.naive_behavior))}</p><p><strong>What Nyst did</strong><br>${escape(String(result.nyst_behavior))}</p></div><ol class="timeline">${rows(result.timeline).map(item=>`<li><span></span><div><strong>${escape(String(item.stage))}</strong><p>${escape(String(item.detail))}</p></div></li>`).join("")}</ol><small>${escape(shortDate(run.created_at))} UTC · seed ${escape(String(run.seed))}</small></article>`}).join(""):`<div class="empty"><h2>Choose a failure boundary</h2><p>Run a deterministic engine scenario to compare naive behavior with Nyst's evidence-bounded decision.</p></div>`}</section><script type="application/json" id="nyst-lab-control">${safeJson(control)}</script>`)}

export function integrationsPage(integrations:Record<string,unknown>[],specs:Record<string,unknown>[]):string{return shell("Integrations",`<header><p class="eyebrow">Connection readiness</p><h1>Integrations</h1><p class="lede">Nyst stores opaque secret references only. A safe check performs credential readiness and, when available, a real provider identity/scope/fixture read without mutation.</p></header><section class="integration-grid">${["github","okta","stripe"].map(provider=>{const item=integrations.find(i=>i.provider===provider);const effects=specs.filter(s=>s.provider===provider);const enabled=effects.filter(s=>s.enabled).length,ready=effects.filter(s=>s.ready).length;const connected=item?.configured===true;const defaultRef=`env:NYST_${provider.toUpperCase()}_${provider==="okta"?"ACCESS_TOKEN":provider==="stripe"?"CREDENTIAL":"TOKEN"}`;return `<article class="panel integration-card"><div class="provider"><span class="provider-icon">${provider[0]!.toUpperCase()}</span><span class="pill ${connected?ready?"good":"warn":"neutral"}">${connected?ready?"Ready":"Configured · blocked":"Not configured"}</span></div><h2>${provider[0]!.toUpperCase()+provider.slice(1)}</h2><dl class="settings-list"><dt>Credential reference</dt><dd>${escape(String(item?.credential_ref??"Not configured"))}</dd><dt>Enabled effects</dt><dd>${enabled}</dd><dt>Ready effects</dt><dd>${ready}</dd><dt>Last read-only preflight</dt><dd>${escape(String(item?.last_verified_at??"Never"))}</dd><dt>Last protected action</dt><dd>${escape(String(item?.last_protected_action_at??"Never"))}</dd><dt>Last reconciliation</dt><dd>${escape(String(item?.last_reconciliation_at??"Never"))}</dd></dl><form class="integration-form" data-provider="${provider}"><label>Opaque secret reference<input name="credential_ref" value="${escape(String(item?.credential_ref??defaultRef))}" required></label><div class="button-row"><button>Save reference</button><button type="button" class="secondary" data-integration-test="${provider}">Run read-only preflight</button></div><p class="form-status" role="status"></p></form></article>`}).join("")}</section>`)}

export function onboardingPage(control:Record<string,unknown>,specs:Record<string,unknown>[]):string{const stage=Number(control.stage??0),completed=Array.isArray(control.completed)?control.completed.map(Boolean):[];const steps=["Select project","Select environment","Choose Shadow or Enforced","Connect provider","Enable EffectSpec","Create API key","Install @nyst-ai/sdk","Send first action","Inspect lifecycle","Verify receipt"];const enabled=specs.filter(s=>s.enabled).length,ready=specs.filter(s=>s.ready).length;const next=stage===2?`<a class="button-link" href="/settings">Choose environment mode</a>`:stage===3?`<a class="button-link" href="/integrations">Configure provider</a>`:stage===4?`<a class="button-link" href="/effect-registry">Enable an EffectSpec</a>`:stage===5?`<a class="button-link" href="/settings#api-keys">Create an API key</a>`:stage===6?`<button id="onboarding-sdk">I installed the SDK</button>`:stage===7?`<p>Send a real supported action through the SDK. Progress advances only after Nyst persists it.</p>`:stage===8?`<a class="button-link" href="/actions">Inspect the action lifecycle</a>`:stage===9?`<a class="button-link" href="/receipts">Verify the signed receipt</a>`:`<a class="button-link" href="/actions">Inspect protected actions</a>`;return shell("Onboarding",`<header><p class="eyebrow">Time to first protected action</p><h1>Make your first consequential action safe.</h1><p class="lede">Connect → route → control → recover → prove. Completion is derived from real persisted product state, except the explicit local SDK-install attestation.</p></header><section class="onboarding"><ol>${steps.map((s,i)=>`<li class="${completed[i]?"done":i===stage?"current":""}"><span>${completed[i]?"✓":i+1}</span><strong>${s}</strong></li>`).join("")}</ol><article class="panel"><span class="mode ${control.is_demo?"demo":escape(String(control.mode))}">${control.is_demo?"DEMO · ":""}${escape(String(control.mode).toUpperCase())}</span><h2>${stage>=10?"First protected action proven":"Continue the next real operation"}</h2><p>${enabled} effects enabled; ${ready} consequence-ready in this environment.</p><pre><code>const nyst = new NystClient({ baseUrl, apiKey });
await nyst.actions.execute({ effect, businessKey, input });</code></pre>${next}<p class="form-status" role="status"></p></article></section>`)}

export function reviewsPage(items:Record<string,unknown>[]):string{return shell("Human Review",`<header><p class="eyebrow">Bounded human escalation</p><h1>Human Review</h1><p class="lede">Understand what is known, acknowledge incidents, or request another observation. There is no force-continue override.</p></header>${items.length?`<section class="card-grid">${items.map(i=>`<article class="panel"><div class="provider"><h2>${escape(String(i.effect_name))}</h2><span class="pill warn">${escape(String(i.status))}</span></div><p>${escape(String(i.reason))}</p><a href="/actions/${encodeURIComponent(String(i.action_id))}">Inspect evidence →</a><div class="button-row"><button data-review="acknowledge" data-id="${escape(String(i.human_review_id))}">Acknowledge</button><button class="secondary" data-review="request_reobservation" data-id="${escape(String(i.human_review_id))}">Request re-observation</button></div></article>`).join("")}</section>`:`<div class="empty"><h2>No actions need review</h2><p>Nyst opens review only when the current durable decision is hold or escalate.</p></div>`}`)}

export function settingsPage(info:Record<string,unknown>|null,control:Record<string,unknown>={},webhooks:Record<string,unknown>[]=[],keys:Record<string,unknown>[]=[]):string{
  const current=webhooks[0];
  return shell("Settings",`<header><p class="eyebrow">Environment control</p><h1>Settings</h1><p class="lede">Mode, outbound decision notifications and deployment-safe references for the selected environment.</p></header><section class="detail-grid"><article class="panel"><h2>Environment mode</h2><span class="mode ${escape(String(control.mode??"enforced"))}">${escape(String(control.mode??"enforced").toUpperCase())}</span><p>Shadow observes supplied facts and reports would-have-blocked decisions. Enforced routes supported effects through Nyst.</p><button id="mode-toggle" data-next="${control.mode==="shadow"?"enforced":"shadow"}">Switch to ${control.mode==="shadow"?"Enforced":"Shadow"}</button></article><article class="panel"><div class="provider"><h2>Decision webhook</h2>${current?`<span class="pill ${current.enabled?"good":"neutral"}">${current.enabled?"Enabled":"Disabled"}</span>`:""}</div><form id="webhook-form" class="control-form"><label>Public HTTPS endpoint<input name="target_url" type="url" value="${escape(String(current?.target_url??""))}" placeholder="https://events.example.com/nyst" required></label><label>Signing secret reference<input name="signing_secret_ref" value="${escape(String(current?.signing_secret_ref??"env:NYST_WEBHOOK_SECRET"))}" required></label><div class="button-row"><button>Save / rotate reference</button>${current?`<button id="webhook-enabled" data-enabled="${current.enabled?"false":"true"}" type="button" class="secondary">${current.enabled?"Disable endpoint":"Enable endpoint"}</button>`:""}${current?.enabled?`<button id="webhook-test" type="button" class="secondary">Queue signed test delivery</button>`:""}</div><p class="form-status" role="status"></p></form><dl class="settings-list"><dt>Last event</dt><dd>${escape(String(current?.last_event_at??"Never"))}</dd><dt>Last attempt</dt><dd>${escape(String(current?.last_attempt_at??"Never"))}</dd><dt>Last result</dt><dd>${escape(String(current?.last_response_status??current?.last_error_code??"Never"))}</dd><dt>Audited attempts</dt><dd>${escape(String(current?.delivery_attempt_count??0))}</dd></dl><p>Events are signed, sequence-bound, durably retried and carry a stable event ID. Receivers must deduplicate on that ID.</p><details><summary>Webhook verification shape</summary><pre><code>signed = timestamp + "." + event_id + "." + raw_body
constant_time_verify(HMAC_SHA256(secret, signed))</code></pre></details></article></section><section id="api-keys"><div class="section-head"><div><p class="eyebrow">Scoped machine access</p><h2>API keys</h2></div><span>Raw keys are shown once</span></div><article class="panel"><form id="api-key-form" class="control-form"><label>Key name<input name="name" value="Design partner SDK" required></label><button>Create scoped SDK key</button><p class="form-status" role="status"></p><code id="created-api-key" class="mono"></code></form>${keys.length?`<div class="table-wrap"><table><thead><tr><th>Name</th><th>Prefix</th><th>Scopes</th><th>Status</th><th></th></tr></thead><tbody>${keys.map(key=>`<tr><td>${escape(String(key.name))}</td><td class="mono">${escape(String(key.prefix))}</td><td>${escape(Array.isArray(key.scopes)?key.scopes.join(", "):String(key.scopes))}</td><td>${key.revoked_at?"Revoked":"Active"}</td><td>${key.revoked_at?"":`<button class="secondary" data-revoke-key="${escape(String(key.api_key_id))}">Revoke</button>`}</td></tr>`).join("")}</tbody></table></div>`:`<p>No API keys in this environment.</p>`}</article></section><section><h2>Current scope</h2>${json(info)}</section>`)}

export function receiptPage(action:Record<string,unknown>,receipt:Record<string,unknown>,valid:boolean|null):string{return shell("Signed receipt",`<header><p class="eyebrow">Evidence-grounded proof</p><h1>Signed receipt</h1><p class="lede">Action ${escape(String(action.action_id))}</p></header><section class="panel"><div class="provider"><h2>Signature verification</h2><span class="pill ${valid===true?"good":valid===false?"bad":"neutral"}">${valid===true?"VALID":valid===false?"INVALID":"NOT CHECKED"}</span></div><p>The signature covers the current resolution, evidence references, control decision and durable sequences.</p><a class="button-link" href="/exports/${encodeURIComponent(String(action.action_id))}">Export JSON</a></section><details><summary>Receipt payload</summary>${json(receipt)}</details>`)}
export function receiptsPage(items:Record<string,unknown>[]):string{return shell("Receipts",`<header><p class="eyebrow">Signed evidence-grounded decisions</p><h1>Receipts</h1></header>${receiptTable(items)}`)}
export function offboardingPage(runs:Record<string,unknown>[]):string{return shell("Controlled offboarding",`<header><p class="eyebrow">Narrow integrated recovery</p><h1>Okta + GitHub offboarding</h1><p class="lede">Each provider action remains independently reconciled and signed. Downstream continuation requires current safe evidence.</p></header>${runs.length?json(runs):`<div class="empty"><h2>No offboarding runs</h2><p>Nothing is fabricated for this environment.</p></div>`}`)}
export function genericPage(title:string,copy:string):string{return shell(title,`<header><p class="eyebrow">Nyst</p><h1>${escape(title)}</h1><p class="lede">${escape(copy)}</p></header>`)}

function shell(title:string,content:string):string{return page(title,`<aside><a class="brand" href="/"><img src="/brand/nyst-wordmark.png" alt="Nyst"></a><!--NYST_CONTEXT--><nav>${nav.map(([href,label])=>`<a href="${href}">${escape(label)}</a>`).join("")}</nav><a class="onboarding-link" href="/onboarding">Setup guide</a><footer><strong>Nyst</strong><span>Effect-control infrastructure</span></footer></aside><main class="content">${content}</main><div id="nyst-dialog" class="dialog-backdrop" hidden><div class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">Confirm change</h2><p id="dialog-copy"></p><div class="button-row"><button id="dialog-cancel" class="secondary">Cancel</button><button id="dialog-confirm">Confirm</button></div></div></div>`,true,"/assets/app.js")}
function page(title:string,body:string,authenticated:boolean,script?:string):string{return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#13233b"><title>${escape(title)} · Nyst</title><link rel="icon" type="image/png" href="/brand/favicon.png"><link rel="stylesheet" href="/assets/app.css"></head><body class="${authenticated?"app":"auth"}">${body}${script?`<script src="${script}" defer></script>`:""}</body></html>`}
function actionTable(items:Record<string,unknown>[]):string{if(!items.length)return `<div class="empty"><h2>No consequential actions yet</h2><p>Route a supported action through the Nyst Gateway or explore the isolated Failure Lab.</p><a href="/onboarding">Open setup guide →</a></div>`;return `<div class="table-wrap"><table><thead><tr><th>Time</th><th>Effect / identity</th><th>Provider</th><th>EffectState</th><th>Safe next action</th></tr></thead><tbody>${items.map(a=>`<tr><td>${escape(shortDate(a.created_at))}</td><td><a href="/actions/${encodeURIComponent(String(a.action_id))}">${escape(String(a.effect_name))}</a><small>${escape(String(a.business_key))}</small></td><td>${escape(String(a.provider??"—"))}</td><td><span class="pill ${stateClass(a.effect_state)}">${escape(String(a.effect_state??"investigating"))}</span></td><td>${escape(String(a.primary_directive??"investigate").replaceAll("_"," "))}</td></tr>`).join("")}</tbody></table></div>`}
function receiptTable(items:Record<string,unknown>[]):string{return items.length?`<div class="table-wrap"><table><thead><tr><th>Time</th><th>Receipt</th><th>EffectState</th><th>Decision</th></tr></thead><tbody>${items.map(a=>`<tr><td>${escape(shortDate(a.created_at))}</td><td><a href="/receipts/${encodeURIComponent(String(a.action_id))}">${escape(String(a.effect_name))}</a></td><td>${escape(String(a.effect_state??"unresolved"))}</td><td>${escape(String(a.primary_directive??"—"))}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty"><h2>No receipts yet</h2><p>Signed receipts appear after durable resolutions.</p></div>`}
function evidenceTimeline(action:Record<string,unknown>,items:Record<string,unknown>[],runtime:Record<string,unknown>):string{const base=[{time:action.created_at,name:"Intent persisted",copy:"Logical identity and semantic hash became durable."},{time:action.created_at,name:"Dispatch ownership",copy:record(action.dispatch_plan).operation?"Provider operation identity persisted before consequence.":"No provider dispatch plan yet."}];const material=items.map(e=>({time:e.observed_at,name:String(e.kind),copy:`${String(e.source)} · ${String(e.observed_disposition)} · ${String(e.attribution)}`}));if(runtime.next_check_at)material.push({time:runtime.next_check_at,name:"Next observation scheduled",copy:"Read-only reconciliation; no redispatch path."});return `<ol class="timeline">${[...base,...material].map((e,i)=>`<li><time>${escape(shortTime(e.time))}</time><span></span><div><strong>${escape(e.name)}</strong><p>${escape(e.copy)}</p></div></li>`).join("")}</ol>`}
function resolutionTable(items:ReturnType<typeof resolutionHistory>):string{return items.length?`<div class="table-wrap"><table><thead><tr><th>Sequence</th><th>EffectState</th><th>Primary</th><th>Retry</th><th>Continuation</th><th>Recovery</th><th>Resolved</th></tr></thead><tbody>${items.map(r=>`<tr><td>${escape(String(r.resolution_sequence))}</td><td>${escape(r.effect_state)}</td><td>${escape(r.primary_directive)}</td><td>${escape(r.retry_disposition)}</td><td>${escape(r.continuation_disposition)}</td><td>${escape(r.recovery_disposition)}</td><td>${escape(shortDate(r.resolved_at))}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">No signed resolution yet.</div>`}
function filterForm(filters:Record<string,unknown>):string{return `<form class="filters" method="get" action="/actions"><label>Provider<input name="provider" value="${escape(String(filters.provider??""))}"></label><label>Effect<input name="effect" value="${escape(String(filters.effect??""))}"></label><label>EffectState<input name="state" value="${escape(String(filters.state??""))}"></label><label>ControlDecision<input name="decision" value="${escape(String(filters.decision??""))}"></label><button>Filter actions</button></form>`}
function json(value:unknown):string{return `<pre>${escape(JSON.stringify(sanitizeForProduct(value),null,2))}</pre>`}function safeJson(value:unknown):string{return escape(JSON.stringify(sanitizeForProduct(value)))}function rows(value:unknown):Record<string,unknown>[]{return Array.isArray(value)?value.filter(x=>x&&typeof x==="object") as Record<string,unknown>[]:[]}function record(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>: {}}function shortDate(value:unknown):string{const d=new Date(String(value));return Number.isFinite(d.getTime())?d.toISOString().replace("T"," ").slice(0,16):"—"}function shortTime(value:unknown):string{const d=new Date(String(value));return Number.isFinite(d.getTime())?d.toISOString().slice(11,19):"—"}function stateClass(value:unknown):string{return value==="verified"?"good":value==="pending"||value==="satisfied_unattributed"?"warn":value==="unprovable"?"bad":"neutral"}function yes(value:unknown):string{return value===true?"Allowed when runtime permits":"No"}function escape(value:string):string{return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!)}
