import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import cookie from "@fastify/cookie";
import Fastify, { type FastifyInstance, type FastifyReply, type FastifyRequest } from "fastify";
import { APP_CSS, APP_JS, LOGIN_JS, PRODUCT_ENHANCEMENT_CSS } from "./assets.js";
import { actionPage, actionsPage, effectRegistryPage, failureLabPage, genericPage, integrationsPage, loginPage, offboardingPage, onboardingPage, overviewPage, policiesPage, receiptPage, receiptsPage, reviewsPage, settingsPage } from "./dashboard.js";
import { digest, ProductRepository } from "./productRepository.js";
import type { PreflightProbeResult } from "./readiness.js";
import type { SecretProvider } from "./secretProvider.js";
import { sanitizeForProduct } from "./sanitize.js";
import type { EffectSpecDescriptor, ProductCommitter, ProductContext, ProductPrincipal } from "./types.js";
import type { InMemoryOperationalMetrics } from "./scheduler.js";

const SESSION_COOKIE = "nyst_session";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const API_SCOPES = new Set(["actions:read", "actions:write", "receipts:read", "integrations:read"]);

export interface ProductServerOptions {
  repository: ProductRepository;
  commit?: ProductCommitter;
  effect_specs: readonly EffectSpecDescriptor[];
  verify_receipt?: (receipt: unknown) => boolean;
  runtime?: { reconcile(actionId: string): Promise<unknown>; authorizeContinuation(actionId: string, resolutionId: string): Promise<void> };
  metrics?: InMemoryOperationalMetrics;
  production?: boolean;
  structured_log?: (event: Record<string, unknown>) => void;
  /** Resolves opaque credential references. Required for readiness/preflight. */
  secrets?: SecretProvider;
  /**
   * Bounded READ-ONLY provider probe. Receives the resolved secret directly and
   * must never mutate provider state (I20).
   */
  integration_preflight?: (provider: "github" | "okta" | "stripe", secret: string) => Promise<PreflightProbeResult>;
}

export async function buildProductServer(options: ProductServerOptions): Promise<FastifyInstance> {
  const app = Fastify({ logger: false, bodyLimit: 64 * 1024, requestIdHeader: false, genReqId: () => randomUUID() });
  await app.register(cookie);
  const limiter = new Map<string, { count: number; reset: number }>();
  app.addHook("onRequest", async (request, reply) => {
    reply.header("X-Nyst-Request-Id", request.id);
    reply.header("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
    reply.header("X-Content-Type-Options", "nosniff"); reply.header("Referrer-Policy", "no-referrer"); reply.header("X-Frame-Options", "DENY");
    const key = request.ip; const now = Date.now(); const current = limiter.get(key);
    if (!current || current.reset <= now) limiter.set(key, { count: 1, reset: now + 60_000 });
    else if (++current.count > 300) { return reply.code(429).send({ error: "rate_limited", request_id: request.id }); }
  });
  app.addHook("onResponse", async(request,reply)=>options.structured_log?.({type:"http_request",request_id:request.id,method:request.method,path:request.routeOptions.url,status_code:reply.statusCode}));
  app.setErrorHandler((error: unknown, request, reply) => { options.metrics?.increment("provider_or_request_errors"); const candidate = error && typeof error === "object" && "statusCode" in error ? Number((error as { statusCode?: unknown }).statusCode) : 500; const status = candidate >= 400 && candidate < 500 ? candidate : 500; reply.code(status).send({ error: status === 500 ? "internal_error" : "invalid_request", request_id: request.id }); });

  app.get("/assets/app.css", async (_request, reply) => reply.type("text/css; charset=utf-8").send(APP_CSS+PRODUCT_ENHANCEMENT_CSS));
  app.get("/assets/login.js", async (_request, reply) => reply.type("application/javascript; charset=utf-8").send(LOGIN_JS));
  app.get("/assets/app.js", async (_request, reply) => reply.type("application/javascript; charset=utf-8").send(APP_JS));
  for(const asset of ["nyst-mark.png","nyst-wordmark.png","nyst-domain-wordmark.png","favicon.png"] as const)app.get(`/brand/${asset}`,async(_request,reply)=>reply.type("image/png").send(readFileSync(join(process.cwd(),"public","brand",asset))));
  app.get("/health",async()=>({status:"ok",service:"nyst-web",version:"0.2.1"}));
  app.get("/ready",async(_request,reply)=>{try{await options.repository.health();return {status:"ready"}}catch{return reply.code(503).send({status:"not_ready"})}});
  app.get("/login", async (_request, reply) => reply.type("text/html; charset=utf-8").send(loginPage()));
  app.post("/v1/auth/login", async (request, reply) => {
    const body = object(request.body); const organization = string(body.organization, 63); const email = string(body.email, 320); const password = string(body.password, 1024);
    const result = await options.repository.login(organization, email, password);
    if (!result) return reply.code(401).send({ error: "invalid_credentials", request_id: request.id });
    reply.setCookie(SESSION_COOKIE, result.session, { path: "/", httpOnly: true, sameSite: "strict", secure: options.production === true, maxAge: 12 * 60 * 60 });
    return { csrf: result.csrf, expires_in: 12 * 60 * 60 };
  });
  app.post("/v1/auth/logout", async (request, reply) => { const principal = await apiPrincipal(request, reply, options.repository); if (!principal) return; requireCsrf(request, principal); const session = request.cookies[SESSION_COOKIE]; if (session) await options.repository.deleteSession(session); reply.clearCookie(SESSION_COOKIE, { path: "/" }); return { ok: true }; });

  app.get("/", pageHandler(async (principal) => overviewPage(await options.repository.impactMetrics(principal)), options.repository));
  app.get("/actions", pageHandler(async (principal,request) => {const selected=filters(request.query);return actionsPage(await options.repository.listActions(principal,selected),"Actions",selected);}, options.repository));
  app.get("/actions/:id", pageHandler(async (principal, request, reply) => { const id = routeId(request); const action = await options.repository.actionDetail(principal, id); if (!action) return reply.code(404).type("text/html").send(genericPage("Not found", "That action does not exist in this environment.")); const evidence = await options.repository.evidence(principal, id) ?? []; const resolutions = await options.repository.resolutions(principal, id) ?? []; return actionPage(action, evidence, resolutions); }, options.repository));
  app.get("/effect-specs", pageHandler(async (principal) => effectRegistryPage(await registryView(options.repository,principal,options.effect_specs,options.production===true)), options.repository));
  app.get("/effect-registry", pageHandler(async (principal) => effectRegistryPage(await registryView(options.repository,principal,options.effect_specs,options.production===true)), options.repository));
  app.get("/policies",pageHandler(async principal=>policiesPage(await options.repository.policyHistory(principal)),options.repository));
  app.get("/failure-lab",pageHandler(async principal=>failureLabPage(await options.repository.failureLabRuns(principal),await options.repository.environmentControl(principal)),options.repository));
  app.get("/evidence", pageHandler(async (principal) => actionsPage(await options.repository.listActions(principal), "Evidence"), options.repository));
  app.get("/receipts", pageHandler(async (principal) => receiptsPage(await options.repository.listActions(principal)), options.repository));
  app.get("/receipts/:id", pageHandler(async (principal,request,reply)=>{const id=routeId(request);const action=await options.repository.actionDetail(principal,id);const receipt=await options.repository.receipt(principal,id);if(!action||!receipt)return reply.code(404).type("text/html").send(genericPage("Not found","That receipt does not exist in this environment."));const valid=options.verify_receipt?options.verify_receipt(receipt):null;return receiptPage(action,receipt,valid);},options.repository));
  app.get("/exports/:id", api(async (principal,request,reply)=>{requireScope(principal,"receipts:read");const receipt=await options.repository.receipt(principal,routeId(request));if(!receipt)return reply.code(404).send({error:"not_found",request_id:request.id});reply.header("Content-Disposition",`attachment; filename="nyst-${routeId(request)}.json"`);return {receipt:sanitizeForProduct(receipt),signature_valid:options.verify_receipt?options.verify_receipt(receipt):null};},options.repository));
  app.get("/integrations", pageHandler(async (principal) => integrationsPage(await options.repository.integrations(principal),await options.repository.effectSpecStatuses(principal,options.effect_specs,options.production===true)), options.repository));
  app.get("/offboarding", pageHandler(async (principal) => offboardingPage(await options.repository.offboardingRuns(principal)), options.repository));
  app.get("/demo", pageHandler(async (principal) => failureLabPage(await options.repository.failureLabRuns(principal),await options.repository.environmentControl(principal)), options.repository));
  app.get("/reviews",pageHandler(async principal=>reviewsPage(await options.repository.humanReviews(principal)),options.repository));
  app.get("/onboarding",pageHandler(async principal=>onboardingPage(await options.repository.onboardingProgress(principal),await options.repository.effectSpecStatuses(principal,options.effect_specs,options.production===true)),options.repository));
  app.get("/settings", pageHandler(async (principal) => settingsPage(await options.repository.projectInfo(principal),await options.repository.environmentControl(principal),await options.repository.webhookStatus(principal),await options.repository.apiKeys(principal)), options.repository));

  app.get("/v1/overview", api(async (principal) => {requireScope(principal,"actions:read");return options.repository.overview(principal);}, options.repository));
  app.get("/v1/actions", api(async (principal, request) => {requireScope(principal,"actions:read");return options.repository.listActions(principal, filters(request.query));}, options.repository));
  app.post("/v1/actions", api(async (principal, request) => { requireScope(principal, "actions:write"); requireCsrf(request, principal); if (!options.commit) throw Object.assign(new Error("Commit unavailable"), { statusCode: 503 }); const body = object(request.body); const effect = string(body.effect, 200); const businessKey = string(body.businessKey, 463); const control=await options.repository.environmentControl(principal);if(control.mode!=="enforced")throw Object.assign(new Error("Shadow environment cannot dispatch provider consequences"),{statusCode:409});const policy=await options.repository.currentPolicy(principal,effect);if(policy.execution_mode==="approval_required"&&(principal.kind!=="session"||body.approved!==true))throw Object.assign(new Error("Human approval required before execution"),{statusCode:409}); const availability = await options.repository.requireEffectSpec(principal, effect, options.effect_specs, options.production === true); const namespacedKey = `${principal.environment_id}:${businessKey}`; const started=Date.now(); const result = await options.commit({ effect, businessKey: namespacedKey, displayBusinessKey: businessKey, input: withCredentialReference(body.input, availability.credential_ref), credential_ref: availability.credential_ref,policy_version_id:policy.policy_version_id,environment_mode:"enforced" }, principal); options.metrics?.observe("action_commit_latency_ms",Date.now()-started);await options.repository.recordResolutionTransition(result.action.action_id,result.resolution,"action_commit"); return sanitizeForProduct(result); }, options.repository));
  app.get("/v1/actions/:id", api(async (principal, request, reply) => {requireScope(principal,"actions:read");return found(reply, sanitizeForProduct(await options.repository.actionDetail(principal, routeId(request))));}, options.repository));
  app.get("/v1/actions/:id/evidence", api(async (principal, request, reply) => {requireScope(principal,"actions:read");return found(reply, sanitizeForProduct(await options.repository.evidence(principal, routeId(request))));}, options.repository));
  app.get("/v1/actions/:id/resolutions", api(async (principal, request, reply) => {requireScope(principal,"actions:read");return found(reply, sanitizeForProduct(await options.repository.resolutions(principal, routeId(request))));}, options.repository));
  app.get("/v1/actions/:id/receipt", api(async (principal, request, reply) => { requireScope(principal, "receipts:read"); const receipt = await options.repository.receipt(principal, routeId(request)); if (!receipt) return reply.code(404).send({ error: "not_found", request_id: request.id }); return { receipt: sanitizeForProduct(receipt), signature_valid: options.verify_receipt ? options.verify_receipt(receipt) : null }; }, options.repository));
  app.post("/v1/actions/:id/reconcile", api(async (principal, request, reply) => { requireScope(principal, "actions:write"); requireCsrf(request, principal); const actionId=routeId(request); if (!(await options.repository.actionDetail(principal,actionId))) return reply.code(404).send({error:"not_found"}); if(!options.runtime) return reply.code(503).send({error:"runtime_unavailable"});const resolution=await options.runtime.reconcile(actionId);await options.repository.recordResolutionTransition(actionId,resolution,"manual_reconcile"); return sanitizeForProduct(resolution); }, options.repository));
  app.post("/v1/actions/:id/continuation-leases", api(async (principal, request, reply) => { requireScope(principal,"actions:write"); requireCsrf(request,principal); const actionId=routeId(request); if (!(await options.repository.actionDetail(principal,actionId))) return reply.code(404).send({error:"not_found"}); if(!options.runtime) return reply.code(503).send({error:"runtime_unavailable"}); const resolutionId=string(object(request.body).resolution_id,36); if(!UUID.test(resolutionId)) throw Object.assign(new Error("Invalid resolution ID"),{statusCode:400}); await options.runtime.authorizeContinuation(actionId,resolutionId); const receipt=await options.repository.receipt(principal,actionId); const runtime=receipt&&typeof receipt.runtime==="object"&&receipt.runtime?receipt.runtime as Record<string,unknown>:null; if(!runtime||!Number.isInteger(runtime.resolution_sequence)||!Number.isInteger(runtime.evidence_sequence)) throw new Error("Current resolution lacks durable sequence binding"); const lease=await options.repository.issueContinuationLease(principal,actionId,resolutionId,Number(runtime.resolution_sequence),Number(runtime.evidence_sequence));await options.repository.queueLifecycleWebhookByAction(actionId,"continuation.authorized");return lease; },options.repository));
  app.post("/v1/continuation-leases/consume", api(async (principal,request,reply)=>{requireScope(principal,"actions:write");requireCsrf(request,principal);const result=await options.repository.consumeContinuationLease(principal,string(object(request.body).lease,120));return result??reply.code(409).send({error:"stale_or_consumed_lease"});},options.repository));
  app.get("/v1/effect-specs", api(async (principal) => {requireAnyScope(principal,["actions:read","integrations:read"]);return options.repository.effectSpecConfiguration(principal, options.effect_specs, options.production === true);}, options.repository));
  app.put("/v1/effect-specs/:effect", api(async (principal,request)=>{if(principal.kind!=="session")throw Object.assign(new Error("Session required"),{statusCode:403});requireCsrf(request,principal);const effect=string(String((request.params as {effect?:unknown}).effect??""),200);const descriptor=options.effect_specs.find(item=>item.effect_name===effect);if(!descriptor)throw Object.assign(new Error("Unknown EffectSpec"),{statusCode:400});const body=object(request.body);if(typeof body.enabled!=="boolean")throw Object.assign(new Error("Boolean enabled required"),{statusCode:400});if(descriptor.provider==="fake"&&options.production===true&&body.enabled)throw Object.assign(new Error("Fake provider unavailable in production"),{statusCode:409});await options.repository.configureEffectSpec(principal,descriptor,body.enabled);return {effect_name:descriptor.effect_name,spec_version:descriptor.spec_version,enabled:body.enabled};},options.repository));
  app.get("/v1/integrations", api(async (principal) => { requireScope(principal, "integrations:read"); return sanitizeForProduct(await options.repository.integrations(principal)); }, options.repository));
  /**
   * "Test" is a READ-ONLY preflight (I20). It resolves the credential through
   * the SecretProvider, calls a bounded read-only probe, persists the
   * categorical outcome, and returns the six readiness dimensions. It never
   * mutates provider state and never returns the credential.
   */
  app.post("/v1/integrations/:provider/preflight",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);const provider=String((request.params as {provider?:unknown}).provider??"");if(provider!=="github"&&provider!=="okta"&&provider!=="stripe")throw Object.assign(new Error("Unsupported provider"),{statusCode:400});if(!options.secrets)throw Object.assign(new Error("No SecretProvider is configured"),{statusCode:503});if(!options.integration_preflight)return {provider,status:"preflight_unavailable",read_only_preflight_performed:false,provider_mutation_performed:false,readiness:await options.repository.integrationReadiness(principal,provider,options.secrets)};const preflight=await options.repository.runIntegrationPreflight(principal,provider,options.secrets,(secret)=>options.integration_preflight!(provider,secret));return {...preflight,readiness:await options.repository.integrationReadiness(principal,provider,options.secrets)};},options.repository));
  // Retained path for existing integrations; same read-only behaviour.
  app.post("/v1/integrations/:provider/test",api(async(principal,request,reply)=>{reply.header("Deprecation","true");reply.header("Link","</v1/integrations/{provider}/preflight>; rel=\"successor-version\"");sessionOnly(principal);requireCsrf(request,principal);const provider=String((request.params as {provider?:unknown}).provider??"");if(provider!=="github"&&provider!=="okta"&&provider!=="stripe")throw Object.assign(new Error("Unsupported provider"),{statusCode:400});if(!options.secrets)throw Object.assign(new Error("No SecretProvider is configured"),{statusCode:503});const readiness=await options.repository.integrationReadiness(principal,provider,options.secrets);if(!readiness.credential_available||!options.integration_preflight)return {...readiness,read_only_preflight_performed:false,provider_mutation_performed:false};const preflight=await options.repository.runIntegrationPreflight(principal,provider,options.secrets,(secret)=>options.integration_preflight!(provider,secret));return {...preflight,readiness:await options.repository.integrationReadiness(principal,provider,options.secrets)};},options.repository));
  app.put("/v1/integrations/:provider", api(async (principal,request)=>{if(principal.kind!=="session")throw Object.assign(new Error("Session required"),{statusCode:403});requireCsrf(request,principal);const provider=String((request.params as {provider?:unknown}).provider??"");if(!["github","okta","stripe"].includes(provider))throw Object.assign(new Error("Unsupported provider"),{statusCode:400});return sanitizeForProduct(await options.repository.configureIntegration(principal,provider,credentialReference(object(request.body).credential_ref)));},options.repository));
  app.get("/v1/offboarding-runs", api(async (principal) => {requireScope(principal,"actions:read");return sanitizeForProduct(await options.repository.offboardingRuns(principal));}, options.repository));
  app.get("/v1/metrics", api(async (principal) => {requireScope(principal,"actions:read");return options.repository.impactMetrics(principal);}, options.repository));
  app.get("/v1/context", api(async (principal)=>{if(principal.kind!=="session")throw Object.assign(new Error("Session required"),{statusCode:403});return options.repository.context(principal);},options.repository));
  app.post("/v1/context", api(async (principal,request,reply)=>{if(principal.kind!=="session")throw Object.assign(new Error("Session required"),{statusCode:403});requireCsrf(request,principal);const body=object(request.body);const projectId=string(body.project_id,36);const environmentId=string(body.environment_id,36);if(!UUID.test(projectId)||!UUID.test(environmentId))throw Object.assign(new Error("Invalid context ID"),{statusCode:400});const session=request.cookies[SESSION_COOKIE];if(!session||!(await options.repository.switchSessionContext(session,principal,projectId,environmentId)))return reply.code(404).send({error:"not_found",request_id:request.id});return {project_id:projectId,environment_id:environmentId};},options.repository));
  app.get("/v1/environment",api(async principal=>options.repository.environmentControl(principal),options.repository));
  app.put("/v1/environment/mode",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);const body=object(request.body);const mode=string(body.mode,8);if(mode!=="shadow"&&mode!=="enforced")throw Object.assign(new Error("Invalid environment mode"),{statusCode:400});return options.repository.setEnvironmentMode(principal,principal.user_id!,mode,string(body.reason,500));},options.repository));
  /**
   * Shadow evaluation. The caller must name the EXACT EffectSpec version the
   * environment has enabled; there is no implicit latest-version substitution.
   */
  app.post("/v1/shadow/evaluations",api(async(principal,request)=>{requireScope(principal,"actions:write");requireCsrf(request,principal);const body=object(request.body);const observation=object(body.observation);const transport=string(observation.transport,30);if(!["success","definitely_not_sent","ambiguous"].includes(transport)||typeof observation.attempted_retry!=="boolean"||typeof observation.attempted_continuation!=="boolean"||!(typeof observation.authoritative_goal_observed==="boolean"||observation.authoritative_goal_observed===null))throw Object.assign(new Error("Invalid Shadow observation"),{statusCode:400});const providerState=observation.provider_state===undefined?{}:{provider_state:object(observation.provider_state)};const effect=string(body.effect,200);const specVersion=string(body.spec_version,200);const agentId=body.agent_id===undefined||body.agent_id===null?null:string(body.agent_id,36);if(agentId!==null&&!UUID.test(agentId))throw Object.assign(new Error("Invalid Agent identifier"),{statusCode:400});return options.repository.recordShadowEvaluation(principal,effect,string(body.businessKey,463),{transport:transport as "success"|"definitely_not_sent"|"ambiguous",authoritative_goal_observed:observation.authoritative_goal_observed as boolean|null,attempted_retry:observation.attempted_retry,attempted_continuation:observation.attempted_continuation,...providerState},specVersion,agentId);},options.repository));
  app.get("/v1/policies",api(async principal=>{requireScope(principal,"actions:read");return options.repository.policyHistory(principal)},options.repository));
  app.post("/v1/policies",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);const body=object(request.body);const effect=body.effect_name===null?null:string(body.effect_name,200);const execution=string(body.execution_mode,30);if(execution!=="automatic"&&execution!=="approval_required"||typeof body.auto_continuation!=="boolean"||typeof body.auto_compensation!=="boolean"||!Number.isInteger(body.reconcile_timeout_seconds))throw Object.assign(new Error("Invalid policy"),{statusCode:400});return options.repository.createPolicyVersion(principal,principal.user_id!,{effect_name:effect,execution_mode:execution,auto_continuation:body.auto_continuation,auto_compensation:body.auto_compensation,reconcile_timeout_seconds:Number(body.reconcile_timeout_seconds)});},options.repository));
  app.get("/v1/webhooks",api(async principal=>{requireScope(principal,"integrations:read");return options.repository.webhookStatus(principal)},options.repository));
  app.put("/v1/webhooks/decision",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);const body=object(request.body);return options.repository.configureWebhook(principal,principal.user_id!,string(body.target_url,2048),string(body.signing_secret_ref,104));},options.repository));
  app.put("/v1/webhooks/decision/enabled",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);const enabled=object(request.body).enabled;if(typeof enabled!=="boolean")throw Object.assign(new Error("Boolean enabled required"),{statusCode:400});return options.repository.setWebhookEnabled(principal,principal.user_id!,enabled);},options.repository));
  app.post("/v1/webhooks/decision/test",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);return options.repository.queueWebhookTest(principal);},options.repository));
  app.post("/v1/actions/:id/recovery-authorizations",api(async(principal,request)=>{requireScope(principal,"actions:write");requireCsrf(request,principal);const body=object(request.body);const operation=string(body.operation,40);if(operation!=="authorized_continuation"&&operation!=="supported_compensation")throw Object.assign(new Error("Unsupported recovery operation"),{statusCode:400});const resolutionId=string(body.resolution_id,36);if(!UUID.test(resolutionId))throw Object.assign(new Error("Invalid resolution ID"),{statusCode:400});return options.repository.authorizeRecovery(principal,routeId(request),resolutionId,operation);},options.repository));
  app.get("/v1/reviews",api(async principal=>{requireScope(principal,"actions:read");return options.repository.humanReviews(principal)},options.repository));
  app.post("/v1/actions/:id/reviews",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);return options.repository.openHumanReview(principal,routeId(request),string(object(request.body).reason,1000));},options.repository));
  app.post("/v1/reviews/:id",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);const operation=string(object(request.body).operation,30);if(operation!=="acknowledge"&&operation!=="request_reobservation")throw Object.assign(new Error("Unsafe or unsupported review operation"),{statusCode:400});return options.repository.updateHumanReview(principal,principal.user_id!,routeId(request),operation);},options.repository));
  app.get("/v1/failure-lab/runs",api(async principal=>{requireScope(principal,"actions:read");return options.repository.failureLabRuns(principal)},options.repository));
  app.post("/v1/failure-lab/runs",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);const body=object(request.body);const scenario=string(body.scenario,40);if(!["response_lost","timeout_before_send","delayed_observation","reconcile_rate_limit","duplicate_caller","process_crash","offboarding_demo"].includes(scenario)||!Number.isInteger(body.seed))throw Object.assign(new Error("Invalid deterministic scenario"),{statusCode:400});return options.repository.runFailureLab(principal,principal.user_id!,scenario as never,string(body.effect,200),Number(body.seed));},options.repository));
  app.put("/v1/onboarding",api(async(principal,request)=>{sessionOnly(principal);requireCsrf(request,principal);if(object(request.body).operation!=="attest_sdk_installed")throw Object.assign(new Error("Unsupported onboarding operation"),{statusCode:400});await options.repository.attestSdkInstalled(principal);return options.repository.onboardingProgress(principal)},options.repository));
  app.get("/v1/api-keys",api(async principal=>{sessionOnly(principal);return options.repository.apiKeys(principal)},options.repository));
  app.post("/v1/api-keys", api(async (principal, request) => { if (principal.kind !== "session") throw Object.assign(new Error("Session required"), { statusCode: 403 }); requireCsrf(request, principal); const body = object(request.body); const scopes=strings(body.scopes,16); if(scopes.some(scope=>!API_SCOPES.has(scope)))throw Object.assign(new Error("Unsupported API key scope"),{statusCode:400}); return options.repository.createApiKey(principal, string(body.name, 120), scopes); }, options.repository));
  app.delete("/v1/api-keys/:id", api(async (principal, request) => { if (principal.kind !== "session") throw Object.assign(new Error("Session required"), { statusCode: 403 }); requireCsrf(request, principal); return { revoked: await options.repository.revokeApiKey(principal, routeId(request)) }; }, options.repository));
  return app;
}

function pageHandler(handler: (principal: ProductPrincipal, request: FastifyRequest, reply: FastifyReply) => Promise<string | FastifyReply>, repository: ProductRepository) { return async (request: FastifyRequest, reply: FastifyReply) => { const principal = await authenticate(request, repository); if (!principal) return reply.redirect("/login");if(principal.kind!=="session")return reply.code(403).type("text/html; charset=utf-8").send(genericPage("Session required","Dashboard pages require a browser session; API keys are limited to versioned API endpoints.")); const value = await handler(principal, request, reply); if (typeof value === "string") { const context=await repository.context(principal); return reply.type("text/html; charset=utf-8").send(value.replace("<!--NYST_CONTEXT-->",contextSwitcher(context))); } return value; }; }
function api(handler: (principal: ProductPrincipal, request: FastifyRequest, reply: FastifyReply) => Promise<unknown>, repository: ProductRepository) { return async (request: FastifyRequest, reply: FastifyReply) => { const principal = await apiPrincipal(request, reply, repository); if (!principal) return; return handler(principal, request, reply); }; }
async function apiPrincipal(request: FastifyRequest, reply: FastifyReply, repository: ProductRepository): Promise<ProductPrincipal | null> { const principal = await authenticate(request, repository); if (!principal) { reply.code(401).send({ error: "unauthorized", request_id: request.id }); return null; } return principal; }
async function authenticate(request: FastifyRequest, repository: ProductRepository): Promise<ProductPrincipal | null> { const auth = request.headers.authorization; if (auth?.startsWith("Nyst ")) return repository.authenticateApiKey(auth.slice(5)); const session = request.cookies[SESSION_COOKIE]; return session ? repository.authenticateSession(session) : null; }
function requireCsrf(request: FastifyRequest, principal: ProductPrincipal): void { if (principal.kind === "api_key") return; const value = request.headers["x-nyst-csrf"]; if (typeof value !== "string" || !principal.csrf_hash || digest(value) !== principal.csrf_hash) throw Object.assign(new Error("CSRF rejected"), { statusCode: 403 }); }
function requireScope(principal: ProductPrincipal, scope: string): void { if (!principal.scopes.includes("*") && !principal.scopes.includes(scope)) throw Object.assign(new Error("Scope denied"), { statusCode: 403 }); }
function requireAnyScope(principal:ProductPrincipal,scopes:readonly string[]):void{if(!principal.scopes.includes("*")&&!scopes.some(scope=>principal.scopes.includes(scope)))throw Object.assign(new Error("Scope denied"),{statusCode:403});}
function sessionOnly(principal:ProductPrincipal):asserts principal is ProductPrincipal&{kind:"session";user_id:string}{if(principal.kind!=="session"||!principal.user_id)throw Object.assign(new Error("Session required"),{statusCode:403});}
function routeId(request: FastifyRequest): string { const id = String((request.params as { id?: unknown }).id ?? ""); if (!UUID.test(id)) throw Object.assign(new Error("Invalid ID"), { statusCode: 400 }); return id; }
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw Object.assign(new Error("Object required"), { statusCode: 400 }); return value as Record<string, unknown>; }
function string(value: unknown, max: number): string { if (typeof value !== "string" || !value || value.length > max || /[\r\n\0]/.test(value)) throw Object.assign(new Error("Invalid string"), { statusCode: 400 }); return value; }
function strings(value: unknown, max: number): string[] { if (!Array.isArray(value) || !value.length || value.length > max || value.some((item) => typeof item !== "string")) throw Object.assign(new Error("Invalid string list"), { statusCode: 400 }); return value as string[]; }
function credentialReference(value:unknown):string{const ref=string(value,300);if(!/^(?:env|vault|secret-manager):[A-Za-z0-9_./:-]{3,280}$/.test(ref))throw Object.assign(new Error("Invalid credential reference"),{statusCode:400});return ref;}
function filters(value: unknown) { const q = value && typeof value === "object" ? value as Record<string, unknown> : {}; const limit=typeof q.limit==="string"?Number(q.limit):undefined;if(limit!==undefined&&(!Number.isInteger(limit)||limit<1||limit>200))throw Object.assign(new Error("Invalid limit"),{statusCode:400});let since: string|undefined;if(typeof q.since==="string"){const parsed=new Date(q.since);if(!Number.isFinite(parsed.getTime()))throw Object.assign(new Error("Invalid since"),{statusCode:400});since=parsed.toISOString();}return { ...(typeof q.provider === "string" ? { provider: filterString(q.provider,60) } : {}), ...(typeof q.effect === "string" ? { effect: filterString(q.effect,200) } : {}), ...(typeof q.state === "string" ? { state: filterString(q.state,40) } : {}), ...(typeof q.decision === "string" ? { decision: filterString(q.decision,40) } : {}), ...(since ? { since } : {}), ...(limit!==undefined ? { limit } : {}) }; }
function filterString(value:string,max:number):string{if(!value||value.length>max||/[\r\n\0]/.test(value))throw Object.assign(new Error("Invalid filter"),{statusCode:400});return value;}
function found(reply: FastifyReply, value: unknown): unknown { return value === null ? reply.code(404).send({ error: "not_found" }) : value; }
function withCredentialReference(value: unknown, credentialRef: string | null): unknown { if (credentialRef===null) return value; const input=object(value); return { ...input, credential_ref: credentialRef }; }
function contextSwitcher(context:ProductContext):string{if(context.projects.length===1&&context.projects[0]?.environments.length===1)return "";const esc=(value:string)=>value.replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"})[c]!);const projects=context.projects.map(project=>`<option value="${esc(project.project_id)}"${project.project_id===context.selected_project_id?" selected":""}>${esc(project.project_name)}</option>`).join("");const safeJson=JSON.stringify(context).replace(/</g,"\\u003c");return `<section class="context-switcher" aria-label="Project and environment context"><label>Project<select id="nyst-project-context">${projects}</select></label><label>Environment<select id="nyst-environment-context"></select></label><script type="application/json" id="nyst-context-data">${safeJson}</script></section>`;}
async function registryView(repository:ProductRepository,principal:ProductPrincipal,descriptors:readonly EffectSpecDescriptor[],production:boolean):Promise<Record<string,unknown>[]>{return repository.effectSpecStatuses(principal,descriptors,production)}
